.data

              ; LOGFONTA stru_4073C3
               stru_4073C3     LOGFONTA <18,8,0,0,FW_BOLD,0,0,0,DEFAULT_CHARSET,OUT_DEFAULT_PRECIS,CLIP_DEFAULT_PRECIS,\
               DEFAULT_QUALITY, 0,"Terminal">            ; DATA XREF: StartAddress+4Fw


               ; char aTsrhTeamPresen[]
               aTsrhTeamPresen db 'TSRh TeaM Presents: PaperBall 1.04 *keYgen*      Greetz: TSR'
                                                      
                               db 'h, REVENGE, tPORt, SnD, CPHV, iCU... %%%))) 6-eyed monster..'
                               db ' other greetz in the about dialog ;)EGOiST',0
               


.data?
               
               @hWnd dd ?
               
               dword_4073B7    dd ?                    ; DATA XREF: StartAddress+93w
                                                       ; sub_401925+23r
               ; HDC dword_4073BB
               dword_4073BB    dd ?                    ; DATA XREF: StartAddress+29w
                                                       ; StartAddress+44r ...


               ; HBITMAP dword_4073BF
               dword_4073BF    dd ?                    ; DATA XREF: StartAddress+3Ew
                                                       ; StartAddress+10Br ...
              
                                                       ; StartAddress+89o
               ; HBRUSH hbr
               hbr             dd ?                    ; DATA XREF: StartAddress+116w
                                                       ; StartAddress+15Er
               ; struct tagPOINT stru_407403
               stru_407403     tagPOINT <?>            ; DATA XREF: StartAddress+11Bo
                                                       ; StartAddress+12Bo
               ; HINSTANCE hInstance
               hInstance       dd ?                    ; DATA XREF: start+7w
                                                       ; sub_40101A+Cr ...
               
                 
