              ; char aTerminal[]
              aTerminal       db 'Terminal',0         ; DATA XREF: sub_401864+6o
              
              ; char aTeam[]
              aTeam           db 0Dh,0Ah              ; DATA XREF: sub_401864+41o
                                                      ; sub_401864+13Do ...
                              db 0Dh,0Ah
                              db 0Dh,0Ah
                              db 0Dh,0Ah
                              db 0Dh,0Ah
                              db 0Dh,0Ah
                              db 0Dh,0Ah
                              ;db ' -- -- ---- --team  ------ ',0Dh,0Ah
                              ;db '------  -- ------   ------ ',0Dh,0Ah
                              ;db ' -- -- ---  -----   ------ ',0Dh,0Ah
                              ;db '  - --  --   --- ----      ',0Dh,0Ah
                              ;db '             ---  --       ',0Dh,0Ah
                              ;db '          -   -            ',0Dh,0Ah
                             
                                                                        
                             db '  ‹‹ ‹‹ ‹‹‹‹ ‹‹team  ‹€≤≤≤‹  ',0Dh,0Ah 
                             db ' ∞€€‹€≤  €€ ∞€€€€≤   €€€€≤≤  ',0Dh,0Ah 
                             db '  €€ €€ ∞€≤  €€‹€€   ﬂ€€€€ﬂ  ',0Dh,0Ah 
                             db '   ﬂ ﬂﬂ  ﬂﬂ   ﬂﬂﬂ ‹≤≤‹       ',0Dh,0Ah 
                             db '              ‹≤‹  ﬂﬂ        ',0Dh,0Ah 
                             db '           ﬂ   ﬂ             ',0Dh,0Ah 
                                                                        
                              db 0Dh,0Ah
                              db 0Dh,0Ah
                              db 0Dh,0Ah
                              db 0Dh,0Ah
                              db 0Dh,0Ah
                              db 0Dh,0Ah
                              db 0Dh,0Ah
                              db 0Dh,0Ah
                              db 0Dh,0Ah
                              db '...::[ Fresh View v5.00 - keygen ]::...',0Dh,0Ah
                              db 0Dh,0Ah
                              db 'Cracked and coded by: FiNS // HTBTeam',0Dh,0Ah
                              db 'Contact: finsss@wp.pl',0Dh,0Ah
                              db 0Dh,0Ah
                              db 'Protection: not found ;)',0Dh,0Ah
                              db 0Dh,0Ah
                              db 'Release date: 2o.o7.2oo5',0Dh,0Ah
                              db 0Dh,0Ah
                              db 'Music by: hollywood',0Dh,0Ah
                              db 0Dh,0Ah
                              db 0Dh,0Ah
                              db 0Dh,0Ah
                              db 0Dh,0Ah
                              db 0Dh,0Ah
                              db 0Dh,0Ah
                              db 0Dh,0Ah
                              db 0Dh,0Ah
                              db 'Greetings to all members of HTBTeam...',0Dh,0Ah
                              db 0Dh,0Ah
                              db '505!k....: your music is really nice            ',0Dh,0Ah
                              db 0Dh,0Ah
                              db 'Amnon....: hello mr idler ;P                    ',0Dh,0Ah
                              db 0Dh,0Ah
                              db 'Cauchy...: unpack.. check.. rename.. repack.. ;)',0Dh,0Ah
                              db 0Dh,0Ah
                              db 'Czajnick.: thx for many things, but why you',27h,'re  ',0Dh,0Ah
                              db '           currently so inactive? :(            ',0Dh,0Ah
                              db 0Dh,0Ah
                              db 'DiViNE...: you',27h,'re dead? or captured by ufo?     ',0Dh,0Ah
                              db 0Dh,0Ah
                              db 'Fre3ze...: maybe write a text about opengl?     ',0Dh,0Ah
                              db 0Dh,0Ah
                              db 'hauer....: the best mr president on the world   ',0Dh,0Ah
                              db 0Dh,0Ah
                              db 'IceNeo...: upload your old rls on dump          ',0Dh,0Ah
                              db 0Dh,0Ah
                              db 'KAT......: htbcom should work now               ',0Dh,0Ah
                              db 0Dh,0Ah
                              db 'Kwasek...: d4crackme - i think i',27h,'ll leave it :| ',0Dh,0Ah
                              db 0Dh,0Ah
                              db 'M@^^.....: can',27h,'t wait to see zine#3 engine      ',0Dh,0Ah
                              db 0Dh,0Ah
                              db 'nOrBi....: long list of rls, nice job           ',0Dh,0Ah
                              db 0Dh,0Ah
                              db 'QUASAR...: pancakes are good :)                 ',0Dh,0Ah
                              db 0Dh,0Ah
                              db 'renno....: waiting for your nfogen and rlspacker',0Dh,0Ah
                              db 0Dh,0Ah
                              db 'Reverend.: really great job with htbEditor      ',0Dh,0Ah
                              db 0Dh,0Ah
                              db 'ReWolf...: crack something for you know.. us!   ',0Dh,0Ah
                              db 0Dh,0Ah
                              db 'reywen...: you little h4k5oR ;)                 ',0Dh,0Ah
                              db 0Dh,0Ah
                              db 'ved......: ZZZzzzine... when??                  ',0Dh,0Ah
                              db 0Dh,0Ah
                              db 0Dh,0Ah
                              db 0Dh,0Ah
                              db 0Dh,0Ah
                              db 'Greetings goes also to all ex-members of HTB',0Dh,0Ah,0
             
             .data?

              ; BITMAPINFO stru_40711B
              stru_40711B     BITMAPINFO <>          ; DATA XREF: sub_401864+73o
              ; struct tagRECT stru_407147

              ; struct tagRECT stru_407147
              stru_407147     tagRECT <>             ; DATA XREF: sub_401864+114w
                                                      ; sub

              dword_415944    dd ?
              
              
              ; DWORD dword_415924
              dword_415924    dd ? 
              dword_415928    dd ?                           
              dword_415938    dd ?
              dword_41593C    dd ?      