         dword_441520    dd 0                    ; DATA XREF: .text:004010CBo
                                                 ; .text:004010DBr ...
         unk_441524      db    0 ;               ; DATA XREF: .text:004013C3o
                                                 ; .text:00401471o ...
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  
                         db    0 ;  


         dword_441628    dd 0                    ; DATA XREF: .text:004013BCo
                                                 ; .text:004013FCw ...
         dword_44162C    dd 0                    ; DATA XREF: .text:0040112Ao
                                                 ; .text:00401136w ...
         dword_441630    dd 0                    ; DATA XREF: .text:004010D6w
                                                 ; .text:00401104r ...
         dword_441634    dd 0                    ; DATA XREF: .text:0040105Cw
                                                 ; .text:0040162Ar
         dbl_441638      dq 0.0                  ; DATA XREF: .text:0040102Dw
                                                 ; .text:0040137Dw ...
         dbl_441640      dq 0.0                  ; DATA XREF: .text:00401039w




         dword_441648    dd 0                    ; DATA XREF: .text:00401027w
                                                 ; .text:00401131r ...
         dword_44164C    dd 0                    ; DATA XREF: .text:0040101Cw
                                                 ; .text:00401114r ...
         dword_441650    dd 0                    ; DATA XREF: .text:00401071w
                                                 ; .text:0040109Er ...
         dword_441654    dd 0                    ; DATA XREF: .text:00401063r
                                                 ; .text:00401689r ...
         dword_441658    dd 0                    ; DATA XREF: .text:00401082w
                                                 ; .text:004010A4r ...
         dword_44165C    dd 0                    ; DATA XREF: .text:0040107Cr
                                                 ; .text:004016C0r ...
         dword_441660    dd 0                    ; DATA XREF: .text:00401095w
                                                 ; .text:004015EAr ...
         dword_441664    dd 0                    ; DATA XREF: .text:0040108Fr
                                                 ; .text:004016F1r ...
         dword_441668    dd 0                    ; DATA XREF: .text:00401000r
                                                 ; .text:00401045w ...


         dbl_42F470      dq -6.28                ; DATA XREF: .text:00401504r
                                                 ; .text:004015B5r
         dbl_42F478      dq 6.0                  ; DATA XREF: .text:004012C6r
                                                 ; .text:004013E5r ...
         dbl_42F480      dq 2.0e-1               ; DATA XREF: .text:00401234r
                                                 ; .text:004014C2r ...
         dbl_42F488      dq 6.28                 ; DATA XREF: .text:004011C5r
                                                 ; .text:004011D8r ...
         dbl_42F490      dq 1.0e-1               ; DATA XREF: .text:004011B4r
                                                 ; .text:004012D7r ...
         dbl_42F498      dq 1.25e2               ; DATA XREF: .text:004011A3r
                                                 ; .text:004014B1r ...
         dbl_42F4A0      dq 1.2e1                ; DATA XREF: .text:0040119Dr
                                                 ; .text:004012C0r ...






