.data

dword_401294    dd 14h

.data?
                  
                  dword_401E00    dd ?                    ; DATA XREF: sub_4018D3+2A5o
                                                          ; sub_4018D3+2E3w
                  dword_401E04    dd ?                    ; DATA XREF: sub_4018D3+2D7w
                  dword_401E08    dd ?                    ; DATA XREF: sub_4018D3+2ECw
                  word_401E0C     dw ?                    ; DATA XREF: sub_4018D3+2FFw
                  word_401E0E     dw ?                    ; DATA XREF: sub_4018D3+305w
                  dword_401E10    dd ?                    ; DATA XREF: sub_4018D3+30Ew
                                  dd 5 dup(?)
                  ; RECT stru_401E28
                  stru_401E28     RECT <?>     


                       


                  ; HDC dword_401E38
                  dword_401E38    dd ?                    ; DATA XREF: TimerFunc+3Dw
                                                          ; TimerFunc+14Er ...
                                  ;align 10h
                  ; BITMAPINFO stru_401E40
                  stru_401E40     BITMAPINFO <>          ; DATA XREF: TimerFunc+10Do
                                                  


                  dword_401DF8    dd ?                    



                  ; RECT stru_401E70
                  stru_401E70     RECT <?>                ; DATA XREF: DialogFunc+1C5w
                                                          ; DialogFunc+275o ...
                  ; int dword_401E80
                  dword_401E80    dd ?                    ; DATA XREF: TimerFunc+15r
                                                          ; TimerFunc+C3r ...
                  ; UINT dword_401E84
                  dword_401E84    dd ?                    ; DATA XREF: TimerFunc+9r
                                                          ; TimerFunc+B8r ...
                  ; HDC dword_401E88
                  dword_401E88    dd ?                    ; DATA XREF: DialogFunc+52w
                                                          ; DialogFunc+AAr ...
                                  
                  ; RECT rc
                  rc              RECT <?>                ; DATA XREF: DialogFunc+63o
                                                          ; DialogFunc+204w ...
                  ; HINSTANCE hInstance
                  hInstance       dd ?                    ; DATA XREF: DialogFunc+230r
                                                          ; sub_4018D3+D0r ...
                                 
                  ; int dword_401EA8
                  dword_401EA8    dd ?                    ; DATA XREF: DialogFunc+91r
                                             



                  ; HGDIOBJ dword_401DB8
                  dword_401DB8    dd ?                    ; DATA XREF: DialogFunc+1ABr
                                                          ; DialogFunc+260r ...
                  byte_401DBC     db ?                    ; DATA XREF: TimerFuncr
                                                          ; TimerFunc+Ew
                                  
                  ; HBRUSH hbr
                  hbr             dd ?                    ; DATA XREF: DialogFunc+5Dr
                                                          ; DialogFunc+345r ...
                                  
                  ; RECT stru_401DC8
                  stru_401DC8     RECT <?>                ; DATA XREF: sub_4018D3+12Cw
                                                          ; sub_4018D3+3C5o ...
                  ; RECT stru_401DD8
                  stru_401DD8     RECT <?>                ; DATA XREF: DialogFunc+1E3w
                                                          ; DialogFunc+2FBo ...
                  dword_401DE8    dd ?                    ; DATA XREF: TimerFunc+42w
                                                          ; TimerFunc:loc_401498r ...
                  ; HBRUSH dword_401DEC
                  dword_401DEC    dd ?                    ; DATA XREF: DialogFunc+26Fr
                                                          ; sub_4018D3+1A4w ...
                  ; HGDIOBJ dword_401DF0
                  dword_401DF0    dd ?                    ; DATA XREF: DialogFunc:loc_401670r
                                                          ; DialogFunc+17Bw
                  ; HDC dword_401DF4
                  dword_401DF4    dd ?       




                  ; HGDIOBJ dword_401EB0
                  dword_401EB0    dd ?                    ; DATA XREF: TimerFunc+F5r
                                                          ; TimerFunc+11Fr ...
                  ; HDC hDC
                  hDC             dd ?                    ; DATA XREF: TimerFunc+101r
                                                          ; TimerFunc+125r ...
                  ; LPVOID lpAddress
                  lpAddress       dd ?                    ; DATA XREF: TimerFunc+5Er
                                                          ; TimerFunc+D4r ...
                  ; LPVOID dword_401EBC
                  dword_401EBC    dd ?                    ; DATA XREF: TimerFunc:loc_401463r
                                                          ; TimerFunc+EDr ...
                  dword_401EC0    dd ?                    ; DATA XREF: TimerFunc+99w
                                                          ; TimerFunc+A7r
                                  
