        dword_402000    dd ?                    ; DATA XREF: sub_4012F1+17Ew
                                                 ; sub_4012F1+1A8o ...
         dword_402004    dd ?                    ; DATA XREF: sub_4012F1+188w
                                                 ; sub_4012F1+2E9r
         dword_402008    dd ?                    ; DATA XREF: sub_4012F1+13Ao
                                                 ; sub_4012F1+157r ...
         dword_40200C    dd ?                    ; DATA XREF: sub_4012F1+198w
                                                 ; sub_4012F1+38Br
         dword_402010    dd ?                    ; DATA XREF: sub_4012F1+296w
                                                 ; sub_4012F1+363r
         dword_402014    dd ?                    ; DATA XREF: sub_4012F1+8Er
                                                 ; sub_4016B2+7w
         dword_402018    dd ?                    ; DATA XREF: sub_4012F1+29Bw
                                                 ; sub_4012F1+31Ar ...
         dword_40201C    dd ?                    ; DATA XREF: sub_4012F1+CBw
                                                 ; sub_4012F1+FFr
         dword_402020    dd ?                    ; DATA XREF: sub_4012F1+DDw
                                                 ; sub_4012F1+25Er ...
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
         unk_402030      db ? ; unexplored       ; DATA XREF: sub_4012F1+259o
                                                 ; sub_4012F1+3A5o
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
         dword_402070    dd ?                    ; DATA XREF: sub_4012F1+332o
                                                 ; sub_4012F1+351r
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
         flt_402078      dd ?                    ; DATA XREF: sub_4012F1+2BDw
                                                 ; sub_4012F1+2C3r ...
         dword_40207C    dd ?                    ; DATA XREF: sub_4012F1+EAw
                                                 ; sub_4012F1+EFr ...
         dword_402080    dd ?                    ; DATA XREF: sub_4012F1+2AAr
                                                 ; sub_4012F1+313o ...
         dword_402084    dd ?                    ; DATA XREF: sub_4012F1+30Bw
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
                         db ? ; unexplored
         dword_402090    dd ?                    ; DATA XREF: sub_4012F1+168w
                                                 ; sub_4012F1+16Dr
         dword_402094    dd ?                    ; DATA XREF: sub_4012F1+FAw
                                                 ; sub_4012F1+105r ...
