               
.data               
               
               aLegoStarwars   db 'Lego Starwars',0    ; DATA XREF: sub_401184+22Do
               
               
               
                byte_406919     db 0FFh, 0, 0FFh        ; DATA XREF: sub_401ADE+8Ao
                                                        ; sub_401BEA+6Eo
                                dd 0FFD2B900h, 0FFF3EC00h, 0FE7A4600h, 0FE6D3700h, 0FC885C00h
                                dd 0FFAC8C00h, 0FE521D00h, 0FE562200h, 0FE5C2500h, 0FE602B00h
                                dd 0FA5C2B00h, 0FF653000h, 0F3633600h, 0FA704400h, 0FF3D0900h
                                dd 0FE441200h, 0FE491500h, 0F8491800h, 0FE4D1A00h, 0F94F1E00h
                                dd 0F24C1E00h, 0F6522400h, 0FE592B00h, 0E8542700h, 0F4562A00h
                                dd 0CC502B00h, 0E05A3200h, 0B94F2F00h, 0E06E4C00h, 0FE390A00h
                                dd 0FC3D0E00h, 0FE400F00h, 0F13D1000h, 0F73F1100h, 0E93A1100h
                                dd 0FA441400h, 49140600h, 0F4441500h, 9D2A0E00h, 370F0500h
                                dd 0D33B1500h, 0E7421800h, 0F1461A00h, 0C03C1900h, 7F271100h
                                dd 0D8461F00h, 0E74A2200h, 0AC3B1D00h, 9B382000h, 0F72E0100h
                                dd 0F22B0100h, 0FE310200h, 0FE2D0200h, 0EF290200h, 0FC2E0300h
                                dd 0E62A0300h, 0E3280300h, 0D9290300h, 88180200h, 0ED2C0400h
                                dd 0F72E0500h, 0F32D0500h, 0FE320600h, 0F9310600h, 0E02A0600h
                                dd 0C6270500h, 0B7240500h, 0FE350700h, 0EC2F0700h, 0FA350800h
                                dd 0F5330800h, 0F02F0800h, 0AB230700h, 0E42F0A00h, 0DC300A00h
                                dd 0F8380C00h, 0F2360C00h, 0BC2A0900h, 6A170500h, 0EA340C00h
                                dd 0D32E0C00h, 0DB330F00h, 0C12F0E00h, 0CA310F00h, 0E6220000h
                                dd 0E1210000h, 0DC1F0000h, 0FE250100h, 0FD290100h, 0F9260100h
                                dd 0F6260100h, 0F2260100h, 0ED250100h, 0EA260100h, 0E9220100h
                                dd 0E6250100h, 0E3250100h, 0DE250100h, 0DE220100h, 0D9210100h
                                dd 0D3220100h, 0C21D0100h, 0BC1C0100h, 0FA2A0200h, 0E3230200h
                                dd 0D8230200h, 0CF210200h, 0C4200200h, 0AF1E0200h, 5D100100h
                                dd 0FF2B0300h, 0F62A0300h, 0E7240300h, 9F1B0200h, 951A0200h
                                dd 0EA280400h, 0E2250400h, 0FF2E0500h, 0EE270500h, 7A160300h
                                dd 0D9270600h, 0D3270600h, 0CD250600h, 0FD230000h, 0F9210000h
                                dd 0F5210000h, 0F2210000h, 0F11E0000h, 0EE210000h, 0ED1E0000h
                                dd 0EA1C0000h, 0EA1E0000h, 0E71F0000h, 0E71C0000h, 0E41F0000h
                                dd 0E41C0000h, 0E21B0000h, 0E11E0000h, 0E01B0000h, 0DE1D0000h
                                dd 0DD1B0000h, 0DA1B0000h, 0DA1E0000h, 0D81B0000h, 0D61B0000h
                                dd 0D61E0000h, 0D51B0000h, 0D31B0000h, 0D11B0000h, 0CF1A0000h
                                dd 0CC1B0000h, 0CC180000h, 0CB180000h, 0CA1A0000h, 0C8180000h
                                dd 0C6180000h, 0C4180000h, 0C3170000h, 0C1170000h, 0BF170000h
                                dd 0BB160000h, 0B8170000h, 0B7170000h, 0B4160000h, 0B0150000h
                                dd 0AD150000h, 0A5140000h, 0A0140000h, 48090000h, 28050000h
                                dd 18030000h, 0D11E0100h, 0CE1D0100h, 0CA1C0100h, 0C91A0100h
                                dd 0C91D0100h, 0C61B0100h, 0C41A0100h, 0C01A0100h, 0BD190100h
                                dd 0B9190100h, 0B3190100h, 0B2160100h, 0B0170100h, 0AA180100h
                                dd 0CB1B0200h, 0F3230300h, 0EC210300h, 0EC1A0000h, 0DF190000h
                                dd 0DE1A0000h, 0DD190000h, 0DB170000h, 0DA190000h, 0D9190000h
                                dd 0D6180000h, 0D5180000h, 0D3180000h, 0D3160000h, 0D0180000h
                                dd 0CF180000h, 0CD160000h, 0CB150000h, 0CB160000h, 0C9150000h
                                dd 0C8160000h, 0C7160000h, 0C6150000h, 0C5150000h, 0C5160000h
                                dd 0C2150000h, 0C1150000h, 0BF140000h, 0BD130000h, 0BC150000h
                                dd 0BC160000h, 0BA150000h, 0BA130000h, 0B8140000h, 0B7140000h
                                dd 0B5120000h, 0B4140000h, 0B3140000h, 0B2110000h, 0B2130000h
                                dd 0B1110000h, 0B0130000h, 0AF120000h, 0AE110000h, 0AD110000h
                                dd 0AC130000h, 0AB110000h, 0AA130000h, 0A8120000h, 0A8110000h
                                dd 0A3110000h, 9C110000h, 930F0000h, 750B0000h, 55080000h
                                dd 9010000h, 0EE160000h, 0E4140000h, 0CD120000h, 0C8100000h
                                dd 0C4110000h, 0C1120000h, 0B8100000h, 840C0000h, 67090000h
                                dd 37050000h, 0E24C3E00h, 0CA0B0000h, 0A60A0000h, 0D9030000h
                                db 0

                 ;db "END palette",0



               byte_406D19     dd 0;3 dup(0)             ; DATA XREF: sub_401BEA+47o
                                
                ;raw data moved to resource
                
                
                
                
                ;db "END raw",0
                
                
                
                dword_40C40B    dd 0                    ; DATA XREF: sub_402036+4r
                                                        ; sub_402036+15r ...
                dword_40C40F    dd 0                    ; DATA XREF: sub_401023+56w
                                                        ; sub_401184+241r ...
                                align 4
                                dd 0Bh dup(0)
                
                                
                ; HINSTANCE hInstance
                hInstance       dd 0                    ; DATA XREF: start+7w
                                                        ; start+12r ...
                ; HGDIOBJ dword_40C474
                dword_40C474    dd 0                    ; DATA XREF: sub_401023+6Ew
                                                        ; sub_401184+18r ...
                ; HWND hWnd
                _hWnd            dd 0                    ; DATA XREF: sub_401184+D7w
                                                        ; sub_401184+ECr ...
                ; HGDIOBJ dword_40C47C
                dword_40C47C    dd 0                    ; DATA XREF: sub_401184+40w
               
               ;=======                                         ; sub_401184+206r ...
                ; HGLOBAL hMem
                hMem            dd 0                    ; DATA XREF: sub_401184+150r
                                                        ; sub_401184+67Br ...
                ; void *dword_40C484
                dword_40C484    dd 0                    ; DATA XREF: sub_401184+156r
                
                ;===============================                                        ; sub_401940+81w ...
                ; HGLOBAL dword_40C488
                dword_40C488    dd 0                    ; DATA XREF: sub_401184+686r
                                                        ; sub_401940+1Aw ...
                ; DWORD ThreadId
                ThreadId        dd 0                    ; DATA XREF: sub_401184+79o
                ; WPARAM wParam
                _wParam          dd 0                    ; DATA XREF: sub_401184+6Fw
                                                        ; sub_401184+95r ...
                ; HDC dword_40C494
                dword_40C494    dd 0                    ; DATA XREF: sub_401184+118w
                                                        ; sub_401184+19Fr ...
                                dd 0
                ; HWND dword_40C49C
                dword_40C49C    dd 0                    ; DATA XREF: sub_401184:loc_4013E3w
                                                        ; sub_401F0D+8r
                ; HANDLE hProcess
                hProcess        dd 0                    ; DATA XREF: sub_401F0D+25w
                                                        ; sub_401F0D+3Br ...
                ; DWORD dwProcessId
                dwProcessId     dd 0                    ; DATA XREF: sub_401F0D+3o
                                                        ; sub_401F0D+13r
                dword_40C4A8    dd 0                    ; DATA XREF: sub_401023+FCw
                                dd 5 dup(0)
                dword_40C4C0    dd 0                    ; DATA XREF: sub_40242C+17r
                                                        ; sub_4025C6w ...
                dword_40C4C4    dd 0                    ; DATA XREF: sub_40242C+32w
                
                
                 dword_406742    dd 0A2F59C2Eh           ; DATA XREF: sub_401D49+Fr
                                                        ; sub_401D49+38w
                dword_406746    dd 5B2A10E9h            ; DATA XREF: sub_401D49+Ar
                                                        ; sub_401D49+3Ew
                ; RECT Rect
                Rect            RECT <7Ch, 5, 131h, 4Dh> ; DATA XREF: StartAddress+DAo
                dword_40675A    dd 0                    ; DATA XREF: sub_401184+44Er
                                                        ; sub_401184+47Br ...

                
                 byte_4067CD     db 3 dup(0)             ; DATA XREF: StartAddress+3Eo
                 dd 262600h, 0
                 dd 25260000h, 2625h, 26000000h, 25252525h, 26h, 25252600h
                 dd 262525h, 25260000h, 25262625h
                 db 25h, 26h, 0

                
                
                
                                                        ; sub_4025C6+4Dw ...
                assume es:nothing
                loc_4067FF=$                             ; CODE XREF: _0.ELO:loc_406789j
                                                        ; DATA XREF: StartAddress+54o
                                db      26h, 26h, 26h, 26h, 26h, 26h, 26h, 26h, 26h
                                add     es:[eax], al
                                add     [esp], ah
                                and     al, 24h
                ; ---------------------------------------------------------------------------
                                dd 0
                                db  24h ; $
                                db 24h, 37h, 39h
                                db  37h ; 7
                                db 37h, 2 dup(24h)
                                db    0
                aX79vv97xX79vv9 db '$X79VV97X$$X79VV97X$',0
                a7797           db '$$7797$$',0
                                



               byte_406845     db 2 dup(0), 25h        ; DATA XREF: StartAddress+6Ao
                                dd 26262626h, 25h, 60000000h, 60h, 0
                                dd 70606070h, 0
                                dd 60007000h, 700060h, 70700000h, 606000h, 4A007070h, 4A004A00h
                                dd 4A004Ah
                                db 4Ah
                byte_406881     db 25h, 2 dup(0)        ; DATA XREF: StartAddress+80o
                                dd 25000025h, 250000h, 26004141h, 41410026h, 0
                                dd 41262641h, 0
                                dd 26414100h, 414126h, 410000h, 262600h, 25004100h, 250000h
                                dd 2500h
                                db 37h
                byte_4068BD     db 0, 32h, 33h          ; DATA XREF: StartAddress+96o
                a456789         db '456789',0
                                align 4
                                dd 25000000h, 25h, 0
                                dd 252500h, 0
                                dd 0A250000h, 250Ah, 25000000h, 640A0A64h, 25h, 36373600h
                                dd 333435h
                                db 0
                byte_4068F9     db 0, 2 dup(26h)        ; DATA XREF: StartAddress+ACo
                                dd 26262600h, 26262626h, 26260026h
                                db 0
                byte_406909     db 0, 2 dup(19h)        ; DATA XREF: StartAddress+C2o
                                dd 19191900h, 19191919h, 19190019h
                                db 0

                                
                                db "End Ripped DATA",0