                 dd offset dword_402000
                 db  98h ; Ø
                 db  20h ;  
                 db  40h ; @
                 db    0 ;  
                 db    0 ;  
                 db  80h ; À
                 db    0 ;  
                 db    0 ;  
                 db    0 ;  
                 db    0 ;  
                 db    0 ;  
                 db    0 ;  
 dword_403010    dd 0                    ; DATA XREF: .text:00401190w
                                         ; .text:004011AAw ...
 dword_403014    dd 0                    ; DATA XREF: start+60w
                 db    0 ;  
                 db    0 ;  
                 db    0 ;  
                 db    0 ;  
 unk_40301C      db    0 ;               ; DATA XREF: start+Bo
                 db    0 ;  
                 db    0 ;  
                 db    0 ;  
 dword_403020    dd 0                    ; DATA XREF: start+44o
                                         ; start+5Ar
 dword_403024    dd 0                    ; DATA XREF: start+3Fo
                                        ; start+54r
 dword_403028    dd 0                    ; DATA XREF: start+3Ao
                                         ; start+4Er
 dword_40302C    dd 0                    ; DATA XREF: .text:004011F8r
                                         ; .text:00401208r
 dword_403030    dd 0                    ; DATA XREF: .text:004010FCw
 dword_403034    dd 0                    ; DATA XREF: .text:00401106w
                                         ; .text:00401121r ...
 dword_403038    dd 0                    ; DATA XREF: .text:0040110Ew

 dword_40308C    dd 0                    ; DATA XREF: .text:004010ABw
 dword_403090    dd 0                    ; DATA XREF: .text:004010B0w
                                         ; .text:004010CCw
 unk_403094      db  0Dh ;               ; DATA XREF: sub_4012F1+C1o

 dword_4030D8    dd 300;0C3h ;dwWidth  195                ; DATA XREF: sub_4012F1+227r
 dword_4030DC    dd 45;19h ;dwHeight 25                 ; DATA XREF: sub_4012F1+151r
                                         ; sub_4012F1+192r
 dword_4030E0    dd 300;0C3h ;signed long x=dwWidth                ; DATA XREF: sub_4012F1+1FFw
                                         ; sub_4012F1+206r ...
 dword_4030E4    dd offset aBigintCalculat;LPCSTR szScroller=   4030F0h              ; DATA XREF: sub_4012F1+12Dr
                                         ; sub_4012F1+140r ...
 flt_4030E8      dd 2.0e1                ; DATA XREF: sub_4012F1+2C9r
 flt_4030EC      dd 1.3e1                ; DATA XREF: sub_4012F1+2E3r
 
 aBigintCalculat  label byte
 
 db 'BigInt Calculator Pro v1.2 *CRACKED*.   Enter your name and ';szScroller
                 db 'hit patch!   huhus to all CORE, UCF, ECL, BS mongos out ther'
                 db 'e =:)) ',0
                 db '://',0













