                 
      .data           
                 dword_408040    dd 2                    ; DATA XREF: sub_401AB0+46r
                                                         ; sub_401AB0+276w ...
                 dword_408044    dd 0                    ; DATA XREF: GmGTwOS:0040196Aw
                                                         ; sub_401AB0+57r ...
                 dbl_408048      dq 6.6e1                ; DATA XREF: sub_401AB0+6Dr
                                                         ; sub_401AB0+F4r ...
                 dbl_408050      dq 1.7e1                ; DATA XREF: sub_401AB0+91r
                                                         ; sub_401AB0+DAr ...

                 dword_4093F0    dd 0                    ; DATA XREF: sub_4020D0+6r
                                                         ; sub_4020D0+10w ...
                                 
                 dbl_4093F8      dq 0.0                  ; DATA XREF: sub_401AB0+A3w
                                                         ; sub_401AB0+214r
                 dbl_409400      dq ?                    ; DATA XREF: sub_401AB0+8Bw
                                                         ; sub_401AB0+202r
                 dword_409408    dd ?                    ; DATA XREF: __cftoe+Dr
                                                         ; __cftof+Dr ...


               ; HWND hWndParent
               hWndParent      dd ?      
            

             dbl_407000      dq 5.0                  ; DATA XREF: sub_401AB0+73r
             dbl_407008      dq 5.555555555555555e-2 ; DATA XREF: sub_401AB0+84r
                                                     ; sub_401AB0+9Dr
             dbl_407010      dq 1.0e1                ; DATA XREF: sub_401AB0+97r
             dbl_407018      dq 3.127659574468085e-1 ; DATA XREF: sub_401AB0+19Br
           

