                
                
                
                dword_407031    dd 0                    ; DATA XREF: sub_4020E9+BCw
                                                        ; sub_402FF0+61r
                dword_407035    dd 0                    ; DATA XREF: sub_4020E9+50w
                dword_407039    dd 0                    ; DATA XREF: sub_4021D8:loc_402626w
                                                        ; sub_4021D8:loc_4026A4w ...
                dword_40703D    dd 0                    ; DATA XREF: sub_4021D8+47Br
                                                        ; sub_4021D8+4BDw ...
                byte_407041     db 1                    ; DATA XREF: sub_4021D8+3A9r
                                                        ; sub_4021D8+591w ...
                byte_407042     db 0                    ; DATA XREF: sub_4021D8+48Dw
                                                        ; sub_4021D8+992r ...
                ; HGLOBAL hMem
                hMem            dd 0                    ; DATA XREF: sub_4021D8+288w
                                                        ; sub_4021D8+385r 
               rcUpdate        RECT <0Ch, 0Ch, 19Ch, 0DEh> ; DATA XREF: sub_4021D8+8A4o
                                                            ; sub_402C7B+1C7r ...

                dword_40706F    dd 190h                 ; DATA XREF: sub_401051+Br
                dword_407073    dd 0                    ; DATA XREF: sub_401051+10r

                
                
                dword_407080    dd 0                    ; DATA XREF: sub_4021D8+749w
                                                        ; sub_4021D8+74Fw ...
                dword_407084    dd 1                    ; DATA XREF: sub_4021D8+734w
                                                        ; sub_4021D8+759w ...
                dword_407088    dd 0                    ; DATA XREF: sub_4021D8+707w
                                                        ; sub_4021D8+877w ...
               
              
                dword_40709B    dd 0                    ; DATA XREF: sub_401051+26r
                                                        ; sub_4021D8+3Dw ...
                dword_40709F    dd 0                    ; DATA XREF: sub_401051:loc_401131r
                                                        ; sub_4021D8+4Dw ...
              
                ; HGDIOBJ dword_4070AF
                dword_4070AF    dd 0                    ; DATA XREF: sub_4021D8+169o
                 
                 
                 
                 
                                                        ; sub_4021D8+178r ...
                ; HDC dword_4070B3
                dword_4070B3    dd 0                    ; DATA XREF: sub_4021D8+164w
                                                        ; sub_4021D8+17Er ...
                ; void *dword_4070B7
                dword_4070B7    dd 0                    ; DATA XREF: sub_401FA3+89r
                                                        ; sub_4021D8+1FDo ...
                ; LPVOID dword_4070BB
                dword_4070BB    dd 0                    ; DATA XREF: sub_4021D8+1B5w
                                                        ; sub_4021D8+222r ...
                ; HGLOBAL dword_4070BF
                dword_4070BF    dd 0                    ; DATA XREF: sub_401051+21w
                 
                 
                byte_4070C3     db 0C0h                 ; DATA XREF: sub_401144+28o
                                dd 0C000C0C0h, 0D8D80000h, 0
                                dd 50F85000h, 50F8h, 1BFFD8FFh, 0CC0000FFh, 0CC6C30D8h
                                dd 0D8F80000h, 0F6DC76h, 0C0C000h, 0
                                dd 0C0C0C070h, 0E0000070h, 0E0303030h, 70D80000h, 0D8h
                                dd 0F8202000h, 2020h, 0C0000000h, 0C0C0h, 0F800h, 0
                                dd 0C0C000h, 30180C00h, 0C060h, 0CCCCCCFCh, 0E00000FCh
                                dd 60606060h, 0CFC0000h, 0FCC0FCh, 0FC0CFC00h, 0FC0Ch
                                dd 0FCD8D8D8h, 0FC000018h, 0FC0CFCC0h, 0C0FC0000h, 0FCCCFCh
                                dd 3018FC00h, 0C060h, 0CCFCCCFCh, 0FC0000FCh, 0FC0CFCCCh
                                dd 0
                                unicode 0, <LL>,0
                                dw 0C000h
                                dd 0C0C000h, 60C06030h, 30h, 0FC00FC00h, 60C00000h, 0C06030h
                                dd 3C0CFC00h, 3000h, 0DBDFC3FFh, 0FC0000DFh, 0CCCCFCCCh
                                dd 0CCF80000h, 0F8CCF8h, 0C0C0FC00h, 0FCC0h, 0CCCCCCF8h
                                dd 0FC0000F8h, 0FCC0FCC0h, 0C0FC0000h, 0C0C0FCh, 0DCC0FC00h
                                dd 0FCCCh, 0CCFCCCCCh, 0C00000CCh, 0C0C0C0C0h, 0C1C0000h
                                dd 0FCCC0Ch, 0F0D8CC00h, 0CCD8h, 0C0C0C0C0h, 0FF0000FCh
                                dd 0DBDBDBDBh, 0ECCC0000h, 0CCDCFCh, 0CCCCFC00h, 0FCCCh
                                dd 0C0FCCCFCh, 0FC0000C0h, 0FCCCCCCCh, 0CCFC0030h, 0DCD8FCh
                                dd 0FCC0FC00h, 0FC0Ch, 303030FCh, 0CC000030h, 0FCCCCCCCh
                                dd 0CCCC0000h, 3078CCh, 0DBDBDB00h, 0FFDBh, 783078C4h
                                dd 0CC0000CCh, 303078CCh, 18FC0000h, 0FC6030h, 0C0C0F000h
                                dd 0F0C0h, 183060C0h, 0F000000Ch, 0F0303030h, 0D8700000h
                                dd 2 dup(0)
                                dd 0FC00h, 3060C0h, 0
                                dd 0FCCCCC3Ch, 0FCC00000h, 0FCCCCCh, 0C0FC0000h, 0FCC0h
                                dd 0CCCCFC0Ch, 0FCh, 0FCF0CCFCh, 607C0000h, 6060FCh, 0CCFC0000h
                                dd 0FC0CFCCCh, 0CCCCFCC0h, 0C00000CCh, 0C0C0C000h, 300000h
                                dd 30303030h, 0F8DCC0F0h, 0DCD8h, 0C0C0C0C0h, 0C0h, 0DBDBDBFFh
                                dd 0FC000000h, 0CCCCCCh, 0CCFC0000h, 0FCCCh, 0CCCCFC00h
                                dd 0C0C0FCh, 0FCCCCCFCh, 0FC000C0Ch, 0C0C0C0h, 0E0FC0000h
                                dd 0FC1Ch, 6060FC60h, 7Ch, 0FCCCCCCCh, 0CC000000h, 3078CCh
                                dd 0D9D90000h, 0FFD9h, 7878CC00h, 0CCh, 0FCCCCCCCh, 0FC00FC04h
                                dd 0FC7038h, 0E0607800h, 7860h, 0C0C0C0C0h, 0F00000C0h
                                dd 0F0303830h, 40000000h, 10A8h
                                db 0
                byte_407355     db 3 dup(0)             ; DATA XREF: sub_401C07+5o
                                                        ; sub_401C07+13o
                 
                                                        ; sub_401144+4Br ...
                byte_4074A3     db 0                    ; DATA XREF: sub_402066+
                                dd 0
                                dd 28000000h, 287C287Ch, 301C0000h, 1C3030h, 0C0C3800h
                                dd 380Ch, 361C36h, 8000000h, 8083E08h, 0
                                dd 3Eh, 18000000h, 18h, 30180C06h, 3C000060h, 3C666666h
                                dd 67C0000h, 7E603Ch, 180C7E00h, 6030h, 663C663Ch, 3Ch
                                dd 18001800h, 30180000h, 183060h, 18306000h, 6030h, 63C603Eh
                                dd 6000007Eh, 663C1830h, 0C7E0000h, 7E3018h, 60607800h
                                dd 7860h, 0C183060h, 78000006h, 78181818h, 0
                                dd 7E0000h, 40400h, 404h, 101C1010h, 7C000010h, 0C107C10h
                                dd 10380000h, 20107Ch, 7C103806h, 2010h, 4444444h, 6000008h
                                dd 8083808h, 87C0000h, 442810h, 147C1000h, 4824h, 804241Ch
                                dd 7C000030h, 7C007C00h, 4600000h, 700804h, 7C007C00h
                                dd 3804h, 3800h, 2800007Ch, 44242424h, 24280600h, 442424h
                                dd 107C1000h, 0C00107Ch, 7C107C10h, 7C030010h, 7C040404h
                                dd 7C100000h, 601010h, 0
                                dd 0C000000h, 8640460h, 8000070h, 40201008h, 47C0000h
                                dd 7C1018h, 24444006h, 7008h, 70100800h, 38060010h, 60100848h
                                dd 7C200600h, 1C2024h, 28483806h, 6010h, 40784040h, 40180040h
                                dd 40407840h, 7C400300h, 3C4040h, 7C007C03h, 3006010h
                                dd 8287C28h, 50030030h, 70080454h, 47C0000h, 681028h, 4047C00h
                                dd 3008h, 1014047Ch, 10000020h, 3804447Ch, 7C100300h, 380444h
                                dd 10107C00h, 7C10h, 28187C08h, 20000048h, 1020247Ch, 8380000h
                                dd 7C0808h, 7C047C00h, 7C04h, 804447Ch, 30h, 44830h, 47C0000h
                                dd 30083Ch, 8483C23h
                                db 10h, 20h, 0

                  
                dword_40769B    dd 0                    ; DATA XREF: sub_401022+5r
                                                        ; sub_401022+1Dw ...
                dword_40769F    dd 0Ah                  ; DATA XREF: sub_401E84+83r
                dword_4076A3    dd 0Ah                  ; DATA XREF: sub_401E84:loc_401ED0r
                byte_4076A7     db 0                    ; DATA XREF: sub_401E84+CCr
                byte_4076A8     db 1                    ; DATA XREF: sub_401E84+5r
                                                        ; sub_401E84+D5r ...
                dword_4076A9    dd 0                    ; DATA XREF: sub_401D07+11w
                
                
                .data?                                        ; sub_401FA3+91r ...
                dword_407750    dd 96h dup(?)           ; DATA XREF: sub_401DE7+14o
                
                 dword_4079A8    dd 465h dup(?)          ; DATA XREF: sub_401D2D+3Do