                  
                 .data
 
                  
                  
                  byte_40CC3A     db 0                    ; DATA XREF: sub_40107Dr
                                                          ; sub_402C5E+36w ...

                  ; HWND dword_40CC3B
                  dword_40CC3B    dd 0            



                  dword_40E2D2    dd 0                    ; DATA XREF: StartAddress+3Ar
                                                          ; StartAddress+58w ...
                  dword_40E2D6    dd 0                    ; DATA XREF: StartAddress+3Fw
                                                          ; sub_403BC8+C9w
                  dword_40E2DA    dd 0                    ; DATA XREF: sub_403BC8+D3w
                  dword_40E2DE    dd 0                    ; DATA XREF: sub_402CD0:loc_402E24r
                        
                        align 4
                                           
                  
                  dword_41D4DE    dd 0            


                  ; void dword_405000
                  dword_405000    dd 0                    ; DATA XREF: sub_401000+2Bo
                  dword_405004    dd 0                    ; DATA XREF: sub_401000+41r
                  

                  
                  
                  
                  
                  dword_405008    dd 0                    ; DATA XREF: sub_401000+5Ar
                                                          ; sub_401000+6Dr
                                  dd 4 dup(0)
                  ; int dword_40501C
                  dword_40501C    dd 1Ch                  ; DATA XREF: sub_401000+30r
                  ; int dword_405020
                  dword_405020    dd 0                    ; DATA XREF: sub_401000+4Fw
                                                          ; sub_40117F+Fr ...
                  ; int dword_405024
                  dword_405024    dd 0                    ; DATA XREF: sub_401000+68w
                                                          ; sub_40117F+2Er ...
                  dword_405028    dd 0                    ; DATA XREF: sub_401000+54w
                                                          ; sub_40117F+18r ...
                  dword_40502C    dd 0                    ; DATA XREF: sub_401000+74w
                  ; int dword_405030
                  dword_405030    dd 0                    ; DATA XREF: sub_40107D+48r
                                                          ; sub_40107D+93w ...
                  ; int dword_405034
                  dword_405034    dd 0                    ; DATA XREF: sub_40107D+4Er
                                                          ; sub_40107D+9Bw ...
                  ; int dword_405038
                  dword_405038    dd 0                    ; DATA XREF: sub_40107D+54r
                                                          ; sub_40107D+A3w ...
                  ; int dword_40503C

                  ; int dword_40503C
                  dword_40503C    dd 0                    ; DATA XREF: sub_40107D+5Ar
                                                          ; sub_40107D+ABw ...



                  ; HWND hWnd
                  ds_hWnd            dd 0                    ; DATA XREF: sub_401000+26w
                                                          ; sub_40107D:loc_401091r ...
                  ; HGDIOBJ dword_405048
                  dword_405048    dd 0                    ; DATA XREF: sub_401000+14w
                                                          ; sub_401000+36r
                  ; HDC hDC
                  hDC             dd 0                    ; DATA XREF: sub_40107D+1Fw
                                                          ; sub_40107D+DAr ...

                  dword_405050    dd 0                    ; DATA XREF: sub_40107D+9w
                                                          ; sub_40107D+24r ...
                  ; HDC dword_405054
                  dword_405054    dd 0                    ; DATA XREF: sub_40107D+C4r
                                                          ; sub_401234+Bw ...
                  ; HDC dword_405058
                  dword_405058    dd 0                    ; DATA XREF: sub_40107D+CFr
                                                          ; sub_40129F+Bw ...
                  byte_40505C     db 0                    ; DATA XREF: TimerFuncr
                                                          ; TimerFunc+9w
                  ; HGDIOBJ dword_40505D
                  dword_40505D    dd 0                    ; DATA XREF: sub_40107D+EBr
                                                          ; sub_401234+27w
                  ; HGDIOBJ dword_405061
                  dword_405061    dd 0                    ; DATA XREF: sub_40107D+F6r
                                                          ; sub_40129F+27w
                  byte_405065     db 3 dup(0)             ; DATA XREF: sub_40107D+3Eo
                                                          ; sub_40107D+8Bo
                                  dd 6Fh dup(0)
                                  db 0

                         
                  off_405225      db "BOB",0;
                   