               
                dword_4044A5    dd 0A2F59C2Eh           ; DATA XREF: sub_401BDC+Fr
                                                        ; sub_401BDC+38w
                dword_4044A9    dd 5B2A10E9h            ; DATA XREF: sub_401BDC+Ar
                                                        ; sub_401BDC+3Ew
                ; RECT Rect
                Rect            RECT <11h, 0B3h, 110h, 0D8h> ; DATA XREF: StartAddress+6Bo
                                
                                db 0
          
                ; HINSTANCE hInstance
                hInstance       dd 0                    ; DATA XREF: start+7w
                                                        ; start+12r ...
             
              
                ; HGDIOBJ dword_40456C
                dword_40456C    dd 0                    ; DATA XREF: sub_401133+48w
                                                        ; sub_401133+214r ...
                ; HGLOBAL hMem
                hMem            dd 0                    ; DATA XREF: sub_401133+117r
                                                        ; sub_401133+7BEr ...
                ; void *dword_404574
                dword_404574    dd 0                    ; DATA XREF: sub_401133+11Dr
                                                        ; sub_401A32+81w ...
                ; HGLOBAL dword_404578
                dword_404578    dd 0                    ; DATA XREF: sub_401133+7C9r
                                                        ; sub_401A32+1Aw ...
                ; DWORD ThreadId
                ThreadId        dd 0                    ; DATA XREF: sub_401133+7Bo
            
                ; HDC dword_404584
                dword_404584    dd 0                    ; DATA XREF: sub_401133+F6w
                                                        ; sub_401133+169r ...
                dword_404588    dd 0FBh dup(0)          ; DATA XREF: sub_401ADD+5o
             
               
          
