              ; void dword_406000
              dword_406000    dd 0                    ; DATA XREF: sub_401000+2Bo
              dword_406004    dd 0                    ; DATA XREF: sub_401000+41r
              dword_406008    dd 0                    ; DATA XREF: sub_401000+5Ar
                                                      ; sub_401000+6Dr
                              dd 4 dup(0)
              ; int dword_40601C
              dword_40601C    dd 1Ch                  ; DATA XREF: sub_401000+30r
              ; int dword_406020
              dword_406020    dd 0                    ; DATA XREF: sub_401000+4Fw
                                                      ; sub_40117F+Fr ...
              ; int dword_406024
              dword_406024    dd 0                    ; DATA XREF: sub_401000+68w
                                                      ; sub_40117F+2Er ...
              dword_406028    dd 0                    ; DATA XREF: sub_401000+54w
                                                      ; sub_40117F+18r ...
              dword_40602C    dd 0                    ; DATA XREF: sub_401000+74w
              ; int dword_406030
              dword_406030    dd 0                    ; DATA XREF: sub_40107D+48r
                                                      ; sub_40107D+93w ...
              ; int dword_406034
              dword_406034    dd 0                    ; DATA XREF: sub_40107D+4Er
                                                      ; sub_40107D+9Bw ...
              ; int dword_406038
              dword_406038    dd 0                    ; DATA XREF: sub_40107D+54r
                                                      ; sub_40107D+A3w ...
              ; int dword_40603C
              dword_40603C    dd 0                    ; DATA XREF: sub_40107D+5Ar
                                                      ; sub_40107D+ABw ...
                              dd 0
              ; HWND hWnd
              ds_hWnd            dd 0                    ; DATA XREF: sub_401000+26w
                                                      ; sub_40107D:loc_401091r ...
              ; HGDIOBJ dword_406048
              dword_406048    dd 0                    ; DATA XREF: sub_401000+14w
                                                      ; sub_401000+36r
              ; HDC hDC
              hDC             dd 0                    ; DATA XREF: sub_40107D+1Fw
                                                      ; sub_40107D+DAr ...
              dword_406050    dd 0                    ; DATA XREF: sub_40107D+9w
                                                      ; sub_40107D+24r ...
              ; HDC dword_406054
              dword_406054    dd 0                    ; DATA XREF: sub_40107D+C4r
                                                      ; sub_401234+Bw ...
              ; HDC dword_406058
              dword_406058    dd 0                    ; DATA XREF: sub_40107D+CFr
                                                      ; sub_40129F+Bw ...
              byte_40605C     db 0                    ; DATA XREF: TimerFuncr
                                                      ; TimerFunc+9w
              ; HGDIOBJ dword_40605D
              dword_40605D    dd 0                    ; DATA XREF: sub_40107D+EBr
                                                      ; sub_401234+27w
              ; HGDIOBJ dword_406061
              dword_406061    dd 0                    ; DATA XREF: sub_40107D+F6r
                                                      ; sub_40129F+27w
              byte_406065     db 3 dup(0)             ; DATA XREF: sub_40107D+3Eo
                                                      ; sub_40107D+8Bo
                              dd 18Fh dup(0)
                              db 0
              ; const CHAR off_4066A5
              off_4066A5      db "BOB",0;dd offset word_424F42   ; DATA XREF: sub_401000+4o
              
 byte_40FFC4     db 0                    ; DATA XREF: sub_40107Dr
                                         ; sub_403D2A+36w ...
; HWND dword_40FFC5
 dword_40FFC5    dd 0             
                
