.data


               ; LPCSTR lpString
               lpString        dd offset aTsrhTeamProudl ; DATA XREF: sub_40210C+88r
                                                       ; sub_40210C+9Aw ...

aTsrhTeamProudl db '   TSRh TeaM Proudly Presents a keYgen for:',0
                                                       ; DATA XREF: sub_40210C:loc_4021AEo
                                                       ; .data:lpStringo
               aPaperball1_04K db 'PaperBall 1.04',0Dh,0Dh,0Dh,0Dh,'Keygenned by: EGOiST',0Dh,'P'
                               db 'rotection: handmade =) contact me to improve.',0
               aGreetzToBHepCr db 'Greetz to:',0Dh,'B-$hep',0Dh,'CReg',0Dh,'V0land',0Dh,'Funbit'
                               db 0Dh,'MozgC',0Dh,'OxEn',0Dh,'infern0',0Dh,'NeRo',0Dh,'Spate',0Dh
                               db 'Nitrogen',0Dh,'Vepergen',0Dh,'Bo0MBoX',0Dh,'mc707',0Dh,'Geo4'
                               db 'ce',0Dh,'Hex',0Dh,'Sprite',0Dh,'Cvas',0Dh,'Black Neuromancer'
                               db 0Dh,'CoaXCable',0Dh,'kpNemo',0Dh,'WELL',0Dh,'MagistR',0Dh,'Mo'
                               db 'onShiner',0Dh,'Noble Ghost',0Dh,'[RU].Ban0K!',0Dh,'Mafia32',0Dh
                               db 'sanniassin',0Dh,'Vittle',0Dh,'GL#0M',0Dh,'V0ldemAr',0Dh,'n0x'
                               db 'i0us',0Dh,'aL',0Dh,'Gelios',0Dh,'QuEST',0Dh,'CERBER',0Dh,'lp'
                               db 'slon',0Dh,'hOrNeT',0Dh,'NukLeoN',0Dh,'Skitz0',0Dh,'MiHaLaS ('
                               db 'gfx)',0Dh,'ALiEN (gfx)',0Dh,'SofT MANiAC (music)',0Dh,0Dh,'S'
                               db 'pecial team greetz:',0Dh,'certainly TSRh',0Dh,'XTiN',0Dh,'RE'
                               db 'VENGE',0Dh,'tPORt',0Dh,'SnD',0Dh,'CPHV',0Dh,'r3mteam',0Dh,'S'
                               db 'GG',0Dh,'WDYL',0Dh,'iCU',0Dh,'Antish@re',0Dh,'and ppl from C'
                               db 'R@CKLAB community..',0Dh,0Dh,'      zor.org/tsrh - zor.org/t'
                               db 'srhclub',0Dh,'irc.street-creed.com - #tsrh - #cracklab (ru)',0Dh
                               db '               www.asmines.com',0Dh,0
                               db    0
               ; char aCourierNew[]
               aCourierNew     db 'courier new',0      ; DATA XREF: sub_402039+72o





               dword_407436    dd 4F47452Eh




               ; void *dword_40779F
               dword_40779F    dd 0                    ; DATA XREF: sub_402039+3Cw
                                                       ; sub_402039+4Ao ...



               ; HDC dword_4077A3
               dword_4077A3    dd 0  

               dword_4077A7    dd 0 

               dword_4077AB    dd 0         
               dword_4077AF    dd 0



